### ISSUE TITLE
Can we make the ALGOLIA_API_KEY, and also the GOOGLEANALYTICS_KEY Github secrets ?

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew.com#3]
https://github.com/openeew/openeew.com/blob/d3689ecaedc68eb506ba59d4e3ccee726a35b8cb/docusaurus.config.js#L14

**Comment by EgidioCaprino** [comment]
Hi @andygrillo, why do we need those keys? Are they used during the build?

I can't add secrets to the repo.

**Comment by andygrillo** [comment]
the Algolia api is for search on the site.

the Google api is for google analytics. 

both are private keys ...

**Comment by andygrillo** [comment]
Sorry, I revised your access to maintainer - should give u access to secrets again
